version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd back/omt
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./back/omt/build/libs/*.jar)
artifacts:
  files:
    - back/omt/build/libs/*.jar
    - back/omt/scripts/**
    - back/omt/appspec.yml
  discard-paths: yes