spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://omtdb.cqhgwdvwwrxh.ap-northeast-2.rds.amazonaws.com:13306/omtDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:100}
        order_inserts: true
        order_updates: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '${GOOGLE_CLIENT_ID}'
            client-secret: '${GOOGLE_CLIENT_SECRET}'
            scope:
              - email
              - profile
          naver:
            client-id: '${NAVER_CLIENT_ID}'
            client-secret: '${NAVER_CLIENT_SECRET}'
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver
          kakao:
            client-id: '${KAKAO_CLIENT_ID}'
            client-secret: '${KAKAO_CLIENT_SECRET}'
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
cors:
  allowed-origins: -'https://omt-onmyticket.vercel.app' -'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: ${JWT_SECRET_KEY}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000
      - https://omt-onmyticket.vercel.app/login

logging.level:
  org.hibernate.SQL:  debug
