name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: omt-githubaction
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Add permission
      run: cd back/omt
           chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    
    - name: Make zip file
      run: zip -r ./deploy.zip .
      shell: bash
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://omt-githubaction/deploy.zip

    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name omt-Application
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name omt-group 
        --s3-location bucket=omt-githubaction,bundleType=zip,key=deploy.zip
